### ISSUE TITLE
How do I create  '~/.passctlrc

### ISSUE THREAD

**Issue by SalviaLover** [nrocco/tpm#4]
Hello,

I installed the package but I couldn't find any ifno on how to create a '~/.passctlrc file with my Team Manager login details. Please advise.

**Comment by nrocco** [comment]
Hello,

Cool that you found this project! I will provide you with a sample config file asap

**Comment by SalviaLover** [comment]
Thanks. Let me know if you need anything for me. A few lines in the readme about the syntax could also do the trick. I tried  adding baseurl, username and a password to the file, but my python programming skills aren't good enough for me to figure out the correct syntax for the '~/.passctlrc file.

**Comment by nrocco** [comment]
Hi @SalviaLover,

I have just uploaded a new version `0.1.1` to pypi that include instructions on how to create a configuration file:

You can view it by typing:

    $ passctl help

I have also added the same instructions to the `README.rst` file in the git repository here:
https://github.com/nrocco/team_password_cli

    % cat ~/.passctlrc
    [passctl]
    baseurl = https://passwords.example.com/index.php
    username = my-username@example.com
    password = xxxxxxxxxxxxxxxxxxx

I am curious if it works for you! Any feedback is highly appreciated.
